[book]
authors = ["Kamil Czerwiński <kamil@czerwinski.dev>"]
language = "en"
multilingual = false
src = "src"
title = "Running k8s cluster at home"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"

